CREATE TABLE IF NOT EXISTS Components (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nom TEXT,
    Commande TEXT UNIQUE,
    Etat_logique BOOLEAN DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Urgence (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom TEXT UNIQUE,
    numero TEXT UNIQUE
    
);